观「内建类型」之书。



「发生事故」乃（承「乙」而化「字符串」而「乙」）也。
「发生事故」者会「信息」而《《外部调用『(fun msg -> print_endline msg; failwith "发生错误！")』》》于「信息」也。 
「尝试运行」乃（承「丙」而化（化「有」而「丙」）而化（化「字符串」而「丙」）而「丙」）也。
「尝试运行」者会「执行」而会「处理」而《《外部调用『(fun f h -> try f () with Failure msg -> h msg)』》》于「执行」于「处理」也。 
